module BS

	}
endse I'm called 'chat' doesn't mean I want to!"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["nasty", "Who are YOU calling 'nasty'?!?"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["sorry", "I may accept your apology. I need to think about it."] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["computer", "Who you callin' 'Computer', chump? This isn't the Enterprise."] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["fuck", "Language! I'll wash your mouth out with soap if you keep that up!"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["shit", "Hey, there are preschool toys present!"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["stupid", "Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["jaime", "you"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["name", "are/am called"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
["hi", "hello"] => {"chat"=>"Just because I'm called 'chat' doesn't mean I want to!", "nasty"=>"Who are YOU calling 'nasty'?!?", "sorry"=>"I may accept your apology. I need to think about it.", "computer"=>"Who you callin' 'Computer', chump? This isn't the Enterprise.", "fuck"=>"Language! I'll wash your mouth out with soap if you keep that up!", "shit"=>"Hey, there are preschool toys present!", "stupid"=>"Mama always said, 'Stupid is as stupid does.' \n\nDo you think Sally Field was typecast?", "jaime"=>"you", "name"=>"are/am called", "hi"=>"hello"}[phrase]},
